spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  liquibase:
    enabled: true
    change-log: /db/changelog/db.changelog-master.xml
  modulith:
    events:
      republish-outstanding-events-on-restart: false # Only useful for single instance applications
      completion-mode: DELETE # DELETE or ARCHIVE also option
application:
  apicallers:
    postzegelserver:
      url: localhost:8080

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    hikari:
      username: postgres
      password: password
    url: jdbc:postgresql://localhost:5432/postzegel_reporter
---
spring:
  config:
    activate:
      on-profile: staging, production
  datasource:
    hikari:
      username: ${DB_USER}
      password: ${DB_PASSWORD}
    url: ${DB_JDBC_URL}